site_name: Popup Rideshare
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
nav:
  - Home: 'index.md'
  - iOS:
    - 'Permissions': 'writing-your-docs.md'
    - 'RWRider': 'styling-your-docs.md'
  - Android:
    - 'License': 'license.md'
    - 'Release Notes': 'release-notes.md'