site_name: Pop-Up Rideshare
theme:
  logo: assets/Popup_Logo.png
  favicon: assets/Popup_Logo.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: light blue
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: light blue
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - search.suggest
    - navigation.top
    - content.code.annotate
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/popuprideshare/
    - icon: fontawesome/brands/github
      link: https://github.com/trilogy-group/rideaustin-android
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Introducing the Popup Rideshare SDK: "index.md"
  - Integrating iOS Sdk:
      - Overview: "ios/overview.md"
      - Concepts: "ios/concepts.md"
      - Getting Started:
          - High Level SDK: "ios/high-level-sdk-getting-started.md"
          - Low Level SDK: "ios/low-level-sdk-getting-started.md"
      - References:
          - High Level SDK: "ios/high-level-sdk-observability.md"
          - Low Level SDK:
              - Register: "ios/register.md"
              - Login: "ios/login.md"
              - ForgotPassword: "ios/forgot-password.md"
              - Client: "ios/client.md"
      - Notifications: "ios/notifications.md"
      - Configuration:
          - High Level SDK: "ios/high-level-sdk-configuration.md"
          - Low Level SDK: "ios/low-level-sdk-configuration.md"
      - Observability: "ios/observability.md"
      - FAQs: "ios/faq.md"
  - Integrating Android Sdk:
      - Overview: "android/overview.md"
      - Concepts: "android/concepts.md"
      - Getting Started:
          - High Level SDK: "android/high-level-sdk-getting-started.md"
          - Low Level SDK: "android/low-level-sdk-getting-started.md"
      - Configuration: "android/configuration.md"
      - Observability: "android/observability.md"
      - FAQs: "android/faq.md"
  - Guides: "guides.md"
  - References: "references.md"
  - Changelog: "changelog.md"
  - Support: "support.md"
  - Gallery: "gallery.md"
